Repository freedomofpress/securedrop-client, pull requests merged in 2019-10, with the labels that each got.

#576 Ignore third party dep warnings
  pytest.ini
Labels: small off-sprint PR

#569 test: run in parallel across 4 workers, 30s -> 12-14s
  Makefile
  README.md
  dev-requirements.in
  dev-requirements.txt
Labels: small off-sprint PR

#595 Remove Loic from CoC contacts (no longer involved)
  CODE_OF_CONDUCT.md
Labels: docs, small off-sprint PR

#566 Handle missing files during an export and open
  securedrop_client/export.py
  securedrop_client/gui/widgets.py
  securedrop_client/logic.py
  securedrop_client/storage.py
  tests/gui/test_widgets.py
  tests/test_export.py
  tests/test_logic.py
  tests/test_storage.py
Labels: bug
