Repository freedomofpress/securedrop-client, pull requests merged in 2020-02, with the labels that each got.

#759 Show warning if source has no public key.
  securedrop_client/gui/widgets.py
  tests/gui/test_widgets.py
Labels: release blocker

#772 update slots and signals to match
  securedrop_client/gui/widgets.py
  securedrop_client/logic.py
  tests/gui/test_widgets.py
  tests/test_logic.py
Labels: release blocker

#777 Fixes #776 fixes mkdir permission in apparmor
  files/usr.bin.securedrop-client
Labels: release blocker

#739 Make sync continuous
  securedrop_client/api_jobs/downloads.py
  securedrop_client/api_jobs/sync.py
  securedrop_client/logic.py
  securedrop_client/queue.py
  securedrop_client/sync.py
  tests/api_jobs/test_downloads.py
  tests/api_jobs/test_sync.py
  tests/test_logic.py
  tests/test_queue.py
  tests/test_sync.py
Labels: release blocker

#780 pure refactor: move auth checks into decorator
  securedrop_client/logic.py
  tests/test_logic.py
Labels: small off-sprint PR

#809 Clarify use of staging env; state of supported features
  README.md
Labels: docs, small off-sprint PR

#819 no longer mark replies as failed if they time out
  securedrop_client/api_jobs/uploads.py
  securedrop_client/logic.py
  tests/test_logic.py
Labels: release blocker

#830 Clearer message in "no keypair" case, fix styling
  securedrop_client/gui/widgets.py
  tests/gui/test_widgets.py
Labels: release blocker
