Repository freedomofpress/securedrop-client, pull requests merged in 2020-01, with the labels that each got.

#680 Disable refresh
  securedrop_client/gui/__init__.py
  securedrop_client/gui/widgets.py
  securedrop_client/resources/__init__.py
  tests/gui/test_init.py
  tests/gui/test_widgets.py
  tests/test_resources.py
Labels: small off-sprint PR

#679 Fixes #659 Adds a show password options for login
  securedrop_client/gui/widgets.py
  securedrop_client/resources/images/eye_hidden.svg
  securedrop_client/resources/images/eye_visible.svg
  tests/gui/test_widgets.py
Labels: needs: ux review

#719 show DD MMM format for source title
  securedrop_client/gui/widgets.py
Labels: small off-sprint PR

#730 build-requirements: update for production beta
  build-requirements.txt
Labels: blocked
