Repository freedomofpress/securedrop-client, pull requests merged in 2022-07, with the labels that each got.

#1497 build: package only translations explicitly marked as supported
  .github/ISSUE_TEMPLATE/release.md
  MANIFEST.in
  Makefile
  requirements/dev-requirements-debian.in
  requirements/dev-requirements-debian.txt
  requirements/dev-requirements.in
  requirements/dev-requirements.txt
  securedrop_client/locale/messages.pot
  securedrop_client/queue.py
Labels: i18n

#1531 feat: enable `pt_PT` and `zh_Hans` as supported languages
  MANIFEST.in
Labels: i18n

#1524 Refactor extract export device from controller
  securedrop_client/gui/conversation/__init__.py
  securedrop_client/gui/conversation/export/__init__.py
  securedrop_client/gui/conversation/export/device.py
  securedrop_client/gui/conversation/export/dialog.py
  securedrop_client/gui/conversation/export/print_dialog.py
  securedrop_client/gui/widgets.py
  securedrop_client/logic.py
  tests/conftest.py
  tests/gui/conversation/export/test_device.py
  tests/gui/conversation/export/test_dialog.py
  tests/gui/test_widgets.py
  tests/integration/conftest.py
  tests/test_logic.py
Labels: :recycle: Refactoring

#1540 Fix (tonight's) nightly build
  Makefile
  requirements/dev-buster-requirements.in
  requirements/dev-buster-requirements.txt
Labels: :strawberry: Bite-sized, :fire: Blocker
