Repository freedomofpress/securedrop-client, pull requests merged in 2022-10, with the labels that each got.

#1574 Upgrade mako==1.2.2
  requirements/build-requirements.txt
  requirements/dev-requirements.txt
  requirements/dev-sdw-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
Labels: :fire: Blocker

#1571 Reflect actual license of the project in setup.py
  setup.py
Labels: licensing

#1573 Upgrade dev dependencies
  requirements/dev-requirements.txt
Labels: dev env, :fire: Blocker

#1565 Fix Bookworm CI pipeline
  .circleci/config.yml
  Makefile
  requirements/dev-bookworm-requirements.in
  requirements/dev-bookworm-requirements.txt
  requirements/dev-bullseye-requirements.in
  requirements/dev-bullseye-requirements.txt
  scripts/codename
Labels: :gear: Tooling

#1576 Fix Bookworm CI pipeline (2)
  requirements/dev-bookworm-requirements.txt
  requirements/dev-bullseye-requirements.txt
Labels: maintainer quality of life, :gear: Tooling
