Repository freedomofpress/securedrop-client, pull requests merged in 2022-09, with the labels that each got.

#1556 Fix outdated comment in generated requirements file
  .circleci/config.yml
  requirements/requirements.txt
Labels: :strawberry: Bite-sized, :gear: Tooling, :beach_umbrella: Summer cleanup

#1525 Remove unnecessary work around segfaults in test suite
  Makefile
  test-functional.sh
  tests/functional/test_user_profile_menu.py
Labels: :strawberry: Bite-sized, :gear: Tooling, :evergreen_tree: Non-blocker, :beach_umbrella: Summer cleanup

#1559 Fix remove untrusted strings from production logs
  securedrop_client/api_jobs/downloads.py
  securedrop_client/api_jobs/uploads.py
  securedrop_client/export.py
  securedrop_client/gui/widgets.py
  securedrop_client/logic.py
  securedrop_client/queue.py
  securedrop_client/storage.py
Labels: security

#1560 Remove unverified string from user interface
  securedrop_client/export.py
  securedrop_client/gui/conversation/export/dialog.py
  securedrop_client/gui/conversation/export/print_dialog.py
  tests/gui/conversation/export/test_dialog.py
  tests/gui/conversation/export/test_print_dialog.py
  tests/test_export.py
Labels: security

#1564 Bump version number to 0.8.1, update change log accordingly
  changelog.md
  securedrop_client/__init__.py
  securedrop_client/locale/messages.pot
  setup.py
Labels: :strawberry: Bite-sized

#1555 Use matrix to add Bookworm jobs to CI
  .circleci/config.yml
  Makefile
  requirements/build-requirements.txt
  requirements/dev-buster-requirements.in
  requirements/dev-buster-requirements.txt
  requirements/dev-requirements.txt
  requirements/dev-sdw-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
Labels: :gear: Tooling
