Repository freedomofpress/securedrop-client, pull requests merged in 2022-12, with the labels that each got.

#1610 Ignore SQLAlchemy vulnerabitity without released mitigation
  Makefile
Labels: security, :fire: Blocker

#1609 Upgrade dependency: certifi
  requirements/build-requirements.txt
  requirements/dev-bookworm-requirements.txt
  requirements/dev-bullseye-requirements.txt
  requirements/dev-sdw-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
Labels: security, :strawberry: Bite-sized

#1592 Improve OSX setup flow based on experience
  Makefile
  requirements/dev-mac-requirements.in
  run.sh
  scripts/setup-tmp-directories.sh
Labels: hackathon

#1603 Allow development environment to work on arm based macOS machines
  Makefile
  README.md
  run.sh
Labels: help wanted, dev env
