Repository freedomofpress/securedrop-client, pull requests merged in 2022-06, with the labels that each got.

#1511 Fix deprecation warnings, comparing int and float values
  securedrop_client/gui/widgets.py
Labels: Bullseye

#1522 Refactor assertions sequence for ease of troubleshooting
  securedrop_client/storage.py
  tests/test_storage.py
Labels: :strawberry: Bite-sized

#1530 Add /dev/xen/hypercall to AppArmor allow-list
  files/usr.bin.securedrop-client
Labels: qubes-4.1
