Repository freedomofpress/securedrop-client, pull requests merged in 2022-11, with the labels that each got.

#1587 Update devdeps
  .gitignore
  README.md
  requirements/dev-bookworm-requirements.txt
  requirements/dev-bullseye-requirements.txt
  requirements/dev-mac-requirements.in
  requirements/dev-requirements.txt
  requirements/dev-sdw-requirements.in
  requirements/dev-sdw-requirements.txt
Labels: security

#1593 Testfix
  tests/test_utils.py
Labels: hackathon

#1597 Remove dependency on py package (deprecated)
  requirements/dev-bookworm-requirements.txt
  requirements/dev-bullseye-requirements.txt
  requirements/dev-sdw-requirements.in
  requirements/dev-sdw-requirements.txt
Labels: :strawberry: Bite-sized, :fire: Blocker

#1596 fix: Accept empty result from sd-devices during export for backwards compatibility
  securedrop_client/export.py
  tests/test_export.py
Labels: bug, :fire: Blocker

#1590 docs: update readme for 2022 Aaron Swartz Day
  README.md
Labels: docs, hackathon

#1588 Spelling
  Doxyfile
  Makefile
  README.md
  changelog.md
  securedrop_client/api_jobs/downloads.py
  securedrop_client/api_jobs/sync.py
  securedrop_client/db.py
  securedrop_client/gui/widgets.py
  securedrop_client/logic.py
  securedrop_client/queue.py
  securedrop_client/state/state.py
  securedrop_client/storage.py
  securedrop_client/utils.py
  setup.py
  tests/api_jobs/test_base.py
  tests/api_jobs/test_sync.py
  tests/api_jobs/test_updatestar.py
  tests/api_jobs/test_uploads.py
  tests/conftest.py
  tests/gui/conversation/export/test_device.py
  tests/gui/test_actions.py
  tests/gui/test_widgets.py
  tests/integration/conftest.py
  tests/state/test_state.py
  tests/test_app.py
  tests/test_crypto.py
  tests/test_export.py
  tests/test_logic.py
Labels: :evergreen_tree: Non-blocker

#1599 Update dev dependencies
  requirements/dev-bookworm-requirements.txt
  requirements/dev-bullseye-requirements.txt
  requirements/dev-sdw-requirements.txt
  securedrop_client/api_jobs/downloads.py
  securedrop_client/gui/base/buttons.py
  securedrop_client/gui/base/misc.py
  securedrop_client/gui/main.py
  securedrop_client/gui/widgets.py
  securedrop_client/locale/messages.pot
  securedrop_client/resources/__init__.py
  securedrop_client/storage.py
  securedrop_client/utils.py
Labels: maintainer quality of life, :gear: Tooling

#1600 Rename desktop entry after freedesktop specifications
  files/press.freedom.SecureDropClient.desktop
Labels: :strawberry: Bite-sized

#1601 Rename desktop entry after freedesktop specifications (2)
  files/securedrop-client.desktop
Labels: :strawberry: Bite-sized

#1589 Rename desktop entry to follow freedesktop specifications
  securedrop_client/app.py
Labels: :strawberry: Bite-sized, :evergreen_tree: Non-blocker
