Repository freedomofpress/securedrop-client, pull requests merged in 2024-09, with the labels that each got.

#2197 Don't use deprecated `logging.warn`
  client/securedrop_client/api_jobs/sync.py
Labels: :strawberry: Bite-sized

#2188 Refactor DeleteSourceDialog so it accepts Set[Source]
  client/securedrop_client/gui/actions.py
  client/securedrop_client/gui/source/delete/dialog.py
  client/securedrop_client/locale/messages.pot
  client/tests/gui/source/delete/test_dialog.py
  client/tests/gui/test_widgets.py
Labels: ux

#2221 docs: document the SDK's upstream/downstream assumptions
  client/securedrop_client/sdk/README.md
Labels: docs

#2225 fix(`test_download_submission_autoresume`): don't hard-code mock's `Content-Length` header
  client/tests/sdk/test_api.py
Labels: tests
